import turtle
win = turtle.Screen()
tyler = turtle.Turtle()
tyler.pencolor("black")
x = win.textinput("Input the x value where you want your road to start:")
y = win.textinput("Input the y value where you want your road to start:")
w = win.textinput("Input how wide you want your road to be:")
h = win.textinput("Input how tall you want your road to be:")
tyler.goto(x,y)
#Asphalt
tyler.begin_fill()
tyler.fillcolor("black")
tyler.forward(200)
tyler.right(90)
tyler.forward(725)
tyler.right(90)
tyler.forward(200)
tyler.right(90)
tyler.forward(725)
tyler.right(90)
tyler.end_fill()
#Movement
tyler.penup()
tyler.forward(85)
tyler.right(90)
#Lines on road
#First Line
tyler.pencolor("yellow")
tyler.begin_fill()
tyler.fillcolor("yellow")
tyler.forward(25)
tyler.pendown()
tyler.forward(75)
tyler.left(90)
tyler.forward(30)
tyler.left(90)
tyler.forward(75)
tyler.left(90)
tyler.forward(30)
tyler.end_fill()
tyler.penup()
tyler.left(90)
tyler.forward(100)
#Second line
tyler.begin_fill()
tyler.fillcolor("yellow")
tyler.forward(50)
tyler.pendown()
tyler.forward(75)
tyler.left(90)
tyler.forward(30)
tyler.left(90)
tyler.forward(75)
tyler.left(90)
tyler.forward(30)
tyler.end_fill()
tyler.penup()
tyler.left(90)
tyler.forward(100)
#Third line
tyler.begin_fill()
tyler.fillcolor("yellow")
tyler.forward(50)
tyler.pendown()
tyler.forward(75)
tyler.left(90)
tyler.forward(30)
tyler.left(90)
tyler.forward(75)
tyler.left(90)
tyler.forward(30)
tyler.end_fill()
tyler.penup()
tyler.left(90)
tyler.forward(100)
#Fourth line
tyler.begin_fill()
tyler.fillcolor("yellow")
tyler.forward(50)
tyler.pendown()
tyler.forward(75)
tyler.left(90)
tyler.forward(30)
tyler.left(90)
tyler.forward(75)
tyler.left(90)
tyler.forward(30)
tyler.end_fill()
tyler.penup()
tyler.left(90)
tyler.forward(100)
#Fifth line
tyler.begin_fill()
tyler.fillcolor("yellow")
tyler.forward(50)
tyler.pendown()
tyler.forward(75)
tyler.left(90)
tyler.forward(30)
tyler.left(90)
tyler.forward(75)
tyler.left(90)
tyler.forward(30)
tyler.end_fill()
win.exitonclick()
