#Blake Dansie
#B3
import turtle
win = turtle.Screen()
tuttle = turtle.Turtle()
tuttle.pencolor("purple")

#Triangle
tuttle.pensize(5)
tuttle.forward(50)
tuttle.left(120)
tuttle.forward(50)
tuttle.left(120)
tuttle.forward(50)
tuttle.left(120)
tuttle.penup()
tuttle.forward(100)
#Square
tuttle.pensize(20)
tuttle.pencolor("green")
tuttle.pendown()
tuttle.forward(50)
tuttle.left(90)
tuttle.forward(50)
tuttle.left(90)
tuttle.forward(50)
tuttle.left(90)
tuttle.forward(50)
tuttle.left(90)
#Decagon
tuttle.pensize(10)
tuttle.pencolor("red")
tuttle.penup()
tuttle.forward(150)
tuttle.pendown()
tuttle.forward(50)
tuttle.left(36)
tuttle.forward(50)
tuttle.left(36)
tuttle.forward(50)
tuttle.left(36)
tuttle.forward(50)
tuttle.left(36)
tuttle.forward(50)
tuttle.left(36)
tuttle.forward(50)
tuttle.left(36)
tuttle.forward(50)
tuttle.left(36)
tuttle.forward(50)
tuttle.left(36)
tuttle.forward(50)
tuttle.left(36)
tuttle.forward(50)
tuttle.left(36)

win.exitonclick()
