#-------------Initals--------------------------------
print("B B B    D D")
print("B   B    D   D")
print("B B B    D    D")
print("B    B   D   D")
print("B B B    D D")
print("")
#-------------Ascii Art------------------------------
print("")
print("          |\\")
print("         |V \\_")
print("         |   \' \\")
print("         )    ,_\\")
print("        /     |")
print("       /       \\")
print("       |        \\")
print("        \\       \\")
print("         |        \\")
print("         |         \\")
print("         | |\\      |")
print("_________/ |_'-     /_________________")
print("")
print("")
#---------------Extra Credit I didn't do----------------------------
