import turtle
win = turtle.Screen()
garrett = turtle.Turtle()
garrett.pencolor("yellow")
garrett.pensize(10)
garrett.fillcolor("yellow")
garrett.begin_fill()
garrett.left(36)
garrett.forward(200)
garrett.right(144)
garrett.forward(200)
garrett.right(144)
garrett.forward(200)
garrett.right(144)
garrett.forward(200)
garrett.right(144)
garrett.forward(200)
garrett.end_fill()
win.exitonclick()
